"""Pokemon string() Column

Revision ID: 319b1af18158
Revises: f3397095ed63
Create Date: 2023-03-04 21:07:06.126637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319b1af18158'
down_revision = 'f3397095ed63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('pokemon_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('pokemon_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
