"""Pokemon added Column

Revision ID: 8812fb06d64b
Revises: 0b444a8731e6
Create Date: 2023-03-04 20:51:23.249225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8812fb06d64b'
down_revision = '0b444a8731e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
